### ISSUE TITLE
No AuthKey Exist Error

### ISSUE THREAD

**Issue by aungthurhahein** [LAC-Japan/MISP-CSVImport#2]
I am trying to utilize this tool with MISP 2.4.129 and getting error 

> Import file parsing
> Import MISP start
> No exist authkey:xxx@email.com

I double checked the key is it's valid auth key.
What seems to be missing here?

**Comment by ssotoya** [comment]
Sorry for the late reply.

This error is an error that the authkey of the user used for import cannot be found in const.py.
Make sure that the email address listed in the user column of the file to be imported (TSV or CSV) matches the email address defined in const.py.
Thank you for your confirmation.
